# SPDX-License-Identifier: Apache-2.0
# Demo/debug SSH overrides (agl-devel posture; see the security note in the
# top-level README). For the demo image only, not for production: root SSH
# login is enabled so a developer can inspect the guest over the demo network.
PermitRootLogin yes
PasswordAuthentication yes
PermitEmptyPasswords yes
UseDNS no
